    - name: Get RVM key
      shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
      sudo: yes
      sudo_user: "{{ build_user }}"
      tags:
      - sproutcore
      - development

    - name: Get RVM install script
      get_url: url=https://get.rvm.io dest=~/rvm-installer
      sudo: yes
      sudo_user: "{{ build_user }}"
      tags:
      - sproutcore
      - development

    - name: Install RVM
      shell: /bin/bash ~/rvm-installer stable --ruby=1.9.3 --autolibs=3
      sudo: yes
      sudo_user: "{{ build_user }}"
      tags:
      - sproutcore
      - development

    - name: Add bashrc RVM entry
      lineinfile: dest=~/.bashrc line='source ~/.rvm/scripts/rvm'
      sudo: yes
      sudo_user: "{{ build_user }}"
      tags:
      - sproutcore
      - development

    - name: Install java
      apt: pkg=openjdk-7-jre
      sudo: yes
      tags:
      - sproutcore
      - development
      
    - name: Install sproutcore
      shell: bash -l -c 'gem install sproutcore -v 1.9.1'
      sudo: yes
      sudo_user: "{{ build_user }}"
      tags:
      - sproutcore
      - development
